"""add shipment_legs

Revision ID: 9dc5be201c21
Revises: fe6b97d045c8
Create Date: 2026-09-19 05:31:23.490549
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9dc5be201c21'
down_revision: Union[str, None] = 'fe6b97d045c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipment_legs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('leg_id', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('boarded_at', sa.DateTime(), nullable=True),
    sa.Column('alighted_at', sa.DateTime(), nullable=True),
    sa.Column('is_aboard', sa.Boolean(), nullable=False),
    sa.Column('is_recovery', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['leg_id'], ['legs.id'], name=op.f('fk_shipment_legs_leg_id_legs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], name=op.f('fk_shipment_legs_shipment_id_shipments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shipment_legs')),
    sa.UniqueConstraint('shipment_id', 'leg_id', name='uq_shipment_leg')
    )
    with op.batch_alter_table('shipment_legs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shipment_legs_is_aboard'), ['is_aboard'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipment_legs_leg_id'), ['leg_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipment_legs_shipment_id'), ['shipment_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shipment_legs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shipment_legs_shipment_id'))
        batch_op.drop_index(batch_op.f('ix_shipment_legs_leg_id'))
        batch_op.drop_index(batch_op.f('ix_shipment_legs_is_aboard'))

    op.drop_table('shipment_legs')
    # ### end Alembic commands ###
