"""add recovery_outcomes

Revision ID: c2d98f12f0a3
Revises: 9dc5be201c21
Create Date: 2026-09-19 06:13:58.237681
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c2d98f12f0a3'
down_revision: Union[str, None] = '9dc5be201c21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recovery_outcomes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('strategy', sa.String(length=16), nullable=False),
    sa.Column('succeeded', sa.Boolean(), nullable=False),
    sa.Column('predicted_cost', sa.Float(), nullable=False),
    sa.Column('predicted_arrival', sa.DateTime(), nullable=True),
    sa.Column('predicted_p_misplace', sa.Float(), nullable=True),
    sa.Column('predicted_temperature', sa.Float(), nullable=False),
    sa.Column('predicted_lambda', sa.Float(), nullable=False),
    sa.Column('actual_cost', sa.Float(), nullable=False),
    sa.Column('actual_arrival', sa.DateTime(), nullable=True),
    sa.Column('actually_misplaced', sa.Boolean(), nullable=False),
    sa.Column('cost_error', sa.Float(), nullable=False),
    sa.Column('eta_error_hours', sa.Float(), nullable=False),
    sa.Column('risk_brier', sa.Float(), nullable=True),
    sa.Column('met_deadline', sa.Boolean(), nullable=False),
    sa.Column('recovery_seconds', sa.Float(), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['recovery_plans.id'], name=op.f('fk_recovery_outcomes_plan_id_recovery_plans'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], name=op.f('fk_recovery_outcomes_shipment_id_shipments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recovery_outcomes'))
    )
    with op.batch_alter_table('recovery_outcomes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recovery_outcomes_shipment_id'), ['shipment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recovery_outcomes_succeeded'), ['succeeded'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recovery_outcomes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recovery_outcomes_succeeded'))
        batch_op.drop_index(batch_op.f('ix_recovery_outcomes_shipment_id'))

    op.drop_table('recovery_outcomes')
    # ### end Alembic commands ###
