"""initial schema

Revision ID: fe6b97d045c8
Revises: 
Create Date: 2026-09-19 04:55:02.422343
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fe6b97d045c8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hubs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('capacity_kg', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_emergent', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hubs'))
    )
    with op.batch_alter_table('hubs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hubs_code'), ['code'], unique=True)
        batch_op.create_index('ix_hubs_location', ['lat', 'lng'], unique=False)

    op.create_table('model_artifacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('storage_path', sa.String(length=512), nullable=False),
    sa.Column('trained_at', sa.DateTime(), nullable=True),
    sa.Column('metrics_json', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_artifacts')),
    sa.UniqueConstraint('name', 'version', name='uq_artifact_name_version')
    )
    with op.batch_alter_table('model_artifacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_artifacts_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_artifacts_name'), ['name'], unique=False)

    op.create_table('hub_candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('mean_risk', sa.Float(), nullable=False),
    sa.Column('hub_score', sa.Float(), nullable=False),
    sa.Column('est_setup_cost', sa.Float(), nullable=False),
    sa.Column('est_annual_savings', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('approved_hub_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_hub_id'], ['hubs.id'], name=op.f('fk_hub_candidates_approved_hub_id_hubs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hub_candidates'))
    )
    with op.batch_alter_table('hub_candidates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hub_candidates_hub_score'), ['hub_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_hub_candidates_status'), ['status'], unique=False)

    op.create_table('shipments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('origin_hub_id', sa.Integer(), nullable=False),
    sa.Column('dest_hub_id', sa.Integer(), nullable=False),
    sa.Column('current_hub_id', sa.Integer(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('volume_m3', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('deadline_at', sa.DateTime(), nullable=False),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('misplaced_at', sa.DateTime(), nullable=True),
    sa.Column('p_misplace', sa.Float(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('lam', sa.Float(), nullable=False),
    sa.Column('pressure', sa.Float(), nullable=False),
    sa.Column('cascade_depth', sa.Integer(), nullable=False),
    sa.Column('sla_penalty_per_hour', sa.Float(), nullable=False),
    sa.Column('base_priority', sa.Float(), nullable=False),
    sa.Column('customer_premium', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['current_hub_id'], ['hubs.id'], name=op.f('fk_shipments_current_hub_id_hubs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dest_hub_id'], ['hubs.id'], name=op.f('fk_shipments_dest_hub_id_hubs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['origin_hub_id'], ['hubs.id'], name=op.f('fk_shipments_origin_hub_id_hubs'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shipments'))
    )
    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shipments_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_shipments_current_hub_id'), ['current_hub_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipments_deadline_at'), ['deadline_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipments_dest_hub_id'), ['dest_hub_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipments_origin_hub_id'), ['origin_hub_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipments_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipments_temperature'), ['temperature'], unique=False)

    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('vehicle_type', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('capacity_kg', sa.Float(), nullable=False),
    sa.Column('capacity_m3', sa.Float(), nullable=False),
    sa.Column('reliability', sa.Float(), nullable=False),
    sa.Column('cost_per_km', sa.Float(), nullable=False),
    sa.Column('current_lat', sa.Float(), nullable=True),
    sa.Column('current_lng', sa.Float(), nullable=True),
    sa.Column('current_hub_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['current_hub_id'], ['hubs.id'], name=op.f('fk_vehicles_current_hub_id_hubs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vehicles'))
    )
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicles_code'), ['code'], unique=True)

    op.create_table('legs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('from_hub_id', sa.Integer(), nullable=False),
    sa.Column('to_hub_id', sa.Integer(), nullable=False),
    sa.Column('departure_at', sa.DateTime(), nullable=False),
    sa.Column('arrival_at', sa.DateTime(), nullable=False),
    sa.Column('capacity_kg', sa.Float(), nullable=False),
    sa.Column('residual_kg', sa.Float(), nullable=False),
    sa.Column('capacity_m3', sa.Float(), nullable=False),
    sa.Column('residual_m3', sa.Float(), nullable=False),
    sa.Column('transit_cost', sa.Float(), nullable=False),
    sa.Column('handling_penalty', sa.Float(), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('polyline', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['from_hub_id'], ['hubs.id'], name=op.f('fk_legs_from_hub_id_hubs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['to_hub_id'], ['hubs.id'], name=op.f('fk_legs_to_hub_id_hubs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name=op.f('fk_legs_vehicle_id_vehicles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_legs'))
    )
    with op.batch_alter_table('legs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_legs_arrival_at'), ['arrival_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_legs_departure_at'), ['departure_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_legs_from_hub_id'), ['from_hub_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_legs_to_hub_id'), ['to_hub_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_legs_vehicle_id'), ['vehicle_id'], unique=False)

    op.create_table('recovery_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('strategy', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('bounty_cost', sa.Float(), nullable=False),
    sa.Column('eta', sa.DateTime(), nullable=True),
    sa.Column('transit_hours', sa.Float(), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('compute_ms', sa.Float(), nullable=False),
    sa.Column('warm_started', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], name=op.f('fk_recovery_plans_shipment_id_shipments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recovery_plans'))
    )
    with op.batch_alter_table('recovery_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recovery_plans_shipment_id'), ['shipment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recovery_plans_status'), ['status'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('firebase_uid', sa.String(length=128), nullable=True),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name=op.f('fk_users_vehicle_id_vehicles'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_firebase_uid'), ['firebase_uid'], unique=True)

    op.create_table('auctions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('max_bounty', sa.Float(), nullable=False),
    sa.Column('opened_at', sa.DateTime(), nullable=False),
    sa.Column('closes_at', sa.DateTime(), nullable=False),
    sa.Column('winning_vehicle_id', sa.Integer(), nullable=True),
    sa.Column('payment', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['recovery_plans.id'], name=op.f('fk_auctions_plan_id_recovery_plans'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], name=op.f('fk_auctions_shipment_id_shipments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['winning_vehicle_id'], ['vehicles.id'], name=op.f('fk_auctions_winning_vehicle_id_vehicles'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auctions'))
    )
    with op.batch_alter_table('auctions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auctions_shipment_id'), ['shipment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_auctions_status'), ['status'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('reason_text', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_audit_logs_actor_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_timestamp'), ['timestamp'], unique=False)

    op.create_table('policy_modes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('weights_json', sa.Text(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_policy_modes_updated_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_policy_modes'))
    )
    op.create_table('recovery_paths',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('leg_id', sa.Integer(), nullable=True),
    sa.Column('from_hub_id', sa.Integer(), nullable=False),
    sa.Column('to_hub_id', sa.Integer(), nullable=False),
    sa.Column('departure_at', sa.DateTime(), nullable=True),
    sa.Column('arrival_at', sa.DateTime(), nullable=True),
    sa.Column('edge_cost', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['from_hub_id'], ['hubs.id'], name=op.f('fk_recovery_paths_from_hub_id_hubs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['leg_id'], ['legs.id'], name=op.f('fk_recovery_paths_leg_id_legs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['plan_id'], ['recovery_plans.id'], name=op.f('fk_recovery_paths_plan_id_recovery_plans'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_hub_id'], ['hubs.id'], name=op.f('fk_recovery_paths_to_hub_id_hubs'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recovery_paths')),
    sa.UniqueConstraint('plan_id', 'seq', name='uq_path_plan_seq')
    )
    with op.batch_alter_table('recovery_paths', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recovery_paths_plan_id'), ['plan_id'], unique=False)

    op.create_table('bids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('auction_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('detour_km', sa.Float(), nullable=False),
    sa.Column('is_winner', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['auction_id'], ['auctions.id'], name=op.f('fk_bids_auction_id_auctions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name=op.f('fk_bids_vehicle_id_vehicles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bids')),
    sa.UniqueConstraint('auction_id', 'vehicle_id', name='uq_bid_auction_vehicle')
    )
    with op.batch_alter_table('bids', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bids_auction_id'), ['auction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bids_vehicle_id'), ['vehicle_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bids', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bids_vehicle_id'))
        batch_op.drop_index(batch_op.f('ix_bids_auction_id'))

    op.drop_table('bids')
    with op.batch_alter_table('recovery_paths', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recovery_paths_plan_id'))

    op.drop_table('recovery_paths')
    op.drop_table('policy_modes')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_timestamp'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('auctions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auctions_status'))
        batch_op.drop_index(batch_op.f('ix_auctions_shipment_id'))

    op.drop_table('auctions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_firebase_uid'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('recovery_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recovery_plans_status'))
        batch_op.drop_index(batch_op.f('ix_recovery_plans_shipment_id'))

    op.drop_table('recovery_plans')
    with op.batch_alter_table('legs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_legs_vehicle_id'))
        batch_op.drop_index(batch_op.f('ix_legs_to_hub_id'))
        batch_op.drop_index(batch_op.f('ix_legs_from_hub_id'))
        batch_op.drop_index(batch_op.f('ix_legs_departure_at'))
        batch_op.drop_index(batch_op.f('ix_legs_arrival_at'))

    op.drop_table('legs')
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicles_code'))

    op.drop_table('vehicles')
    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shipments_temperature'))
        batch_op.drop_index(batch_op.f('ix_shipments_status'))
        batch_op.drop_index(batch_op.f('ix_shipments_origin_hub_id'))
        batch_op.drop_index(batch_op.f('ix_shipments_dest_hub_id'))
        batch_op.drop_index(batch_op.f('ix_shipments_deadline_at'))
        batch_op.drop_index(batch_op.f('ix_shipments_current_hub_id'))
        batch_op.drop_index(batch_op.f('ix_shipments_code'))

    op.drop_table('shipments')
    with op.batch_alter_table('hub_candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hub_candidates_status'))
        batch_op.drop_index(batch_op.f('ix_hub_candidates_hub_score'))

    op.drop_table('hub_candidates')
    with op.batch_alter_table('model_artifacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_artifacts_name'))
        batch_op.drop_index(batch_op.f('ix_model_artifacts_is_active'))

    op.drop_table('model_artifacts')
    with op.batch_alter_table('hubs', schema=None) as batch_op:
        batch_op.drop_index('ix_hubs_location')
        batch_op.drop_index(batch_op.f('ix_hubs_code'))

    op.drop_table('hubs')
    # ### end Alembic commands ###
