"""E1 scoring service: turns domain objects into E1 features and back.

DOCUMENTED ASSUMPTION
---------------------
E1 was trained on a logistics dataset whose columns do not map one-to-one
onto the SH-205 `Shipment` entity. The training features are:

    route, hub, carrier, congestion_index, num_handoffs,
    sorting_method, weather_flag, hour_of_day

The SH-205 schema has no carrier, congestion or weather fields, so this
module defines the mapping explicitly rather than inventing columns:

    route            <- "<origin_hub.code>-<dest_hub.code>"
    hub              <- current hub code (falls back to origin)
    carrier          <- vehicle type mapped onto a training carrier value
    congestion_index <- supplied by the simulator; defaults to the training mean
    num_handoffs     <- number of legs already traversed
    sorting_method   <- "unknown" (the artifact's contract placeholder)
    weather_flag     <- supplied by the simulator; defaults to 0
    hour_of_day      <- hour of the scoring timestamp

Hub and route codes generated by the SH-205 simulator will not match the
training vocabulary (`R000..R499`, `F000..F199`). The fitted OneHotEncoder
handles unknown categories, but the resulting probabilities are driven by
the numeric features only. This is a known and recorded limitation.
"""

from __future__ import annotations

from datetime import datetime
from typing import TYPE_CHECKING, Any, Dict, List, Optional, Sequence

from app.engines.e1_misplacement.features import (
    SORTING_METHOD_PLACEHOLDER,
    E1Features,
)
from app.engines.e1_misplacement.registry import ModelRegistry, get_registry
from app.models.base import utcnow
from app.models.enums import VehicleType

if TYPE_CHECKING:  # pragma: no cover
    from app.models import Hub, Shipment

# Mean congestion_index observed in the training data. Used when the caller
# has no telemetry, so the feature sits at a neutral value.
DEFAULT_CONGESTION_INDEX = 0.37

# The training vocabulary for `carrier`.
CARRIER_BY_VEHICLE_TYPE: Dict[str, str] = {
    VehicleType.OWNED.value: "road",
    VehicleType.THIRD_PARTY.value: "multi",
}
DEFAULT_CARRIER = "multi"


def build_features(
    *,
    origin_code: str,
    dest_code: str,
    current_hub_code: Optional[str] = None,
    vehicle_type: Optional[str] = None,
    congestion_index: float = DEFAULT_CONGESTION_INDEX,
    num_handoffs: int = 0,
    weather_flag: int = 0,
    at: Optional[datetime] = None,
) -> E1Features:
    """Assembles an :class:`E1Features` row from domain values."""
    moment = at or utcnow()
    return E1Features(
        route=f"{origin_code}-{dest_code}",
        hub=current_hub_code or origin_code,
        carrier=CARRIER_BY_VEHICLE_TYPE.get(vehicle_type or "", DEFAULT_CARRIER),
        congestion_index=float(congestion_index),
        num_handoffs=int(num_handoffs),
        sorting_method=SORTING_METHOD_PLACEHOLDER,
        weather_flag=int(bool(weather_flag)),
        hour_of_day=moment.hour,
    )


def features_for_shipment(
    shipment: "Shipment",
    *,
    origin: "Hub",
    dest: "Hub",
    current: Optional["Hub"] = None,
    congestion_index: float = DEFAULT_CONGESTION_INDEX,
    weather_flag: int = 0,
    num_handoffs: Optional[int] = None,
    at: Optional[datetime] = None,
) -> E1Features:
    """Builds E1 features for a persisted shipment.

    Hubs are passed in rather than lazy-loaded so callers scoring many
    shipments can fetch them once instead of issuing a query per row.
    """
    return build_features(
        origin_code=origin.code,
        dest_code=dest.code,
        current_hub_code=(current or origin).code,
        congestion_index=congestion_index,
        num_handoffs=(
            shipment.cascade_depth if num_handoffs is None else num_handoffs
        ),
        weather_flag=weather_flag,
        at=at,
    )


class E1Service:
    """Thin façade over the registry used by the tick loop and the API."""

    def __init__(self, registry: Optional[ModelRegistry] = None) -> None:
        self._registry = registry or get_registry()

    def score(self, features: E1Features) -> float:
        """P(misplace) for a single row."""
        return self._registry.predict(features.as_row())

    def score_many(self, rows: Sequence[E1Features]) -> List[float]:
        """P(misplace) for many rows in one vectorised pass."""
        return self._registry.predict_batch([row.as_row() for row in rows])

    def score_raw(self, payload: Dict[str, Any]) -> float:
        """Scores an already-shaped feature dict (used by the API)."""
        return self._registry.predict(payload)

    @property
    def is_ready(self) -> bool:
        return self._registry.is_loaded
